name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies in backend folder
      working-directory: ./backend
      run: npm ci

    - name: Build backend
      working-directory: ./backend
      run: npm run build

    - name: Configure environment variables
      working-directory: ./backend
      run: |
        touch .env
        echo "${{ secrets.AFFWORLD_SECRETS }}" > .env

    - name: Start or Restart PM2 Process
      working-directory: ./backend
      run: |
        pm2 delete BackenedAPI || true
        pm2 start dist/server.js --name BackenedAPI
